version: '3.3'

services:
  back:
    build:
      context: .
    ports:
      - '8000:8000'
    restart: always
    environment:
      MONGO_DB: "mongodb+srv://gevorgatikyan1:Ye4PLtvfSCqy7WhN@cluster0.3zf45.mongodb.net/bestscore?authSource=admin"
      PORT: 8000